### ISSUE TITLE
Please add sign & verify func

### ISSUE THREAD

**Issue by dilcheck** [aergoio/heraj#4]
I need to use sign & verify func for signature app

**Comment by acktsap** [comment]
You mean signing / verifying plain message in a string? Like, `signMessage` and `verifyMessage` in the [bitcoinj](https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/core/ECKey.java)?

**Comment by dilcheck** [comment]
Yes, that's what I wanna be func

**Comment by acktsap** [comment]
I've just added it in a commit 7603f90e7cedbf1a0d404ead512cccdb1f46d550. It will be available on v0.12.0.
