### ISSUE TITLE
About HDWallet

### ISSUE THREAD

**Issue by dilcheck** [aergoio/heraj#6]
https://github.com/bitcoinj/bitcoinj/blob/master/core/src/main/java/org/bitcoinj/crypto/HDKeyDerivation.java

heraj has function like this?

**Comment by acktsap** [comment]
If you mean creating aergokey from seed deterministically, it would be nice feature. But if you mean real hierarchical deterministic wallet, we have to discuss it more.

Maybe we can combine hd wallet with Wallet Implementation or provide some kind of keychain. And we have to think about how to handle balance of wallet.

**Comment by dilcheck** [comment]
Uhm...
I will check my project again
Thx for your reply.
